#!/usr/bin/env python3
"""
Bootstrap AWS accounts for CDK deployments with cross-account AssumeRole support.

This script:
- Reads bootstrap_config.json generated by discover_stages.py
- Bootstraps the principal account directly
- Assumes GitLabCrossAccount in target accounts before bootstrapping them
"""

import json
import os
import subprocess
import sys

import boto3
from botocore.exceptions import ClientError


def bootstrap_account(account_id: str, region: str, cmd: str, env: dict) -> bool:
    """
    Execute CDK bootstrap command for an account.

    Args:
        account_id: AWS account ID
        region: AWS region
        cmd: CDK bootstrap command to execute
        env: Environment variables (including AWS credentials if assumed role)

    Returns:
        True if successful, False otherwise
    """
    print(f"   Command: {cmd}")
    result = subprocess.run(cmd, shell=True, env=env)

    if result.returncode != 0:
        print("⚠️  Bootstrap failed or already exists (continuing...)")
        return False
    else:
        print("✅ Bootstrap completed successfully")
        return True


def bootstrap_principal_account(account_id: str, region: str) -> bool:
    """Bootstrap the principal AWS account (no AssumeRole needed)."""
    print("📌 Bootstrapping principal account (no assume role needed)...")
    cmd = f"cdk bootstrap aws://{account_id}/{region}"
    env = os.environ.copy()
    return bootstrap_account(account_id, region, cmd, env)


def bootstrap_target_account(account_id: str, region: str, principal_account: str) -> bool:
    """Bootstrap a target AWS account using AssumeRole and prepare required IAM roles."""
    print(f"🔑 Assuming role GitLabCrossAccount in account {account_id}...")
    role_arn = f"arn:aws:iam::{account_id}:role/GitLabCrossAccount"

    try:
        # sts = boto3.client("sts")
        print(f"✅ region for assume role (account {account_id}): {region}")
        os.environ["AWS_STS_REGIONAL_ENDPOINTS"] = "regional"
        session = boto3.Session(region_name=region)
        sts = session.client("sts")
        # sts = boto3.client("sts", region_name=region)
        assumed_role = sts.assume_role(RoleArn=role_arn, RoleSessionName="gitlab-cdk-bootstrap")

        print(f"✅ Successfully assumed role: {role_arn}")

        # Extract temporary credentials
        creds = assumed_role["Credentials"]

        # Prepare environment with temporary credentials for CDK bootstrap
        env = os.environ.copy()
        env["AWS_ACCESS_KEY_ID"] = creds["AccessKeyId"]
        env["AWS_SECRET_ACCESS_KEY"] = creds["SecretAccessKey"]
        env["AWS_SESSION_TOKEN"] = creds["SessionToken"]

        # Use the assumed role credentials with boto3 as well
        assumed_session = boto3.Session(
            aws_access_key_id=creds["AccessKeyId"],
            aws_secret_access_key=creds["SecretAccessKey"],
            aws_session_token=creds["SessionToken"],
            region_name=region,
        )

        # Create required service-linked roles if they don't already exist
        iam = assumed_session.client("iam")

        def ensure_service_linked_role(service_name: str) -> None:
            """Ensure a given service-linked role exists in the target account."""
            try:
                print(
                    f"🔧 Ensuring service-linked role for {service_name} "
                    f"in account {account_id} / region {region}..."
                )
                iam.create_service_linked_role(AWSServiceName=service_name)
                print(f"✅ Service-linked role for {service_name} created")
            except ClientError as e:
                code = e.response.get("Error", {}).get("Code")
                # Role already exists or not needed – we can safely ignore
                if code in ("InvalidInput", "EntityAlreadyExists"):
                    print(
                        f"ℹ️  Service-linked role for {service_name} already exists or is not required: {code}"
                    )
                else:
                    print(f"⚠️  Failed to create service-linked role for {service_name}: {e}")
                    raise

        # ECS / AutoScaling / ELB service-linked roles commonly required for ECS workloads
        ensure_service_linked_role("ecs.amazonaws.com")
        # ensure_service_linked_role("autoscaling.amazonaws.com")
        # ensure_service_linked_role("elasticloadbalancing.amazonaws.com")

        print(f"📌 Bootstrapping with trust to principal account {principal_account}...")
        cmd = (
            f"cdk bootstrap aws://{account_id}/{region} "
            f"--trust {principal_account} "
            f"--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess"
        )

        return bootstrap_account(account_id, region, cmd, env)

    except Exception as e:
        print(f"❌ Failed to assume role: {e}")
        print(f"⚠️  Make sure GitLabCrossAccount exists in account {account_id}")
        print(f"⚠️  Trust policy must allow: arn:aws:iam::{principal_account}:user/ops-cicd")
        return False


def main():
    """Main bootstrap orchestration function."""
    # Check if bootstrap config exists
    if not os.path.exists("bootstrap_config.json"):
        print("⚠️  No bootstrap_config.json found - skipping")
        return 0

    # Load bootstrap config
    with open("bootstrap_config.json", "r") as f:
        config = json.load(f)

    principal = config["principal_account"]
    print(f"🔐 Principal account: {principal}")
    print()

    # Bootstrap each account
    success_count = 0
    for account in config["accounts"]:
        account_id = account["account_id"]
        account_region = account.get("region", "eu-west-1")
        is_principal = account["is_principal"]
        needs_trust = account["needs_trust"]

        print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print(f"🔧 Account: {account_id}")
        print(f"   Region: {account_region}")
        print(f"   Principal: {is_principal}")
        print(f"   Needs trust: {needs_trust}")
        print()

        if is_principal:
            # Principal account: bootstrap only in its primary region
            success = bootstrap_principal_account(account_id, account_region)
        else:
            # here create service linked role if needed
            # aws iam --region {account_region} create-service-linked-role --aws-service-name ecs.amazonaws.com
            # aws iam --region {account_region} create-service-linked-role --aws-service-name autoscaling.amazonaws.com
            # aws iam --region {account_region} create-service-linked-role --aws-service-name elasticloadbalancing.amazonaws.com

            # Bootstrap in the account's region (where stacks are deployed)
            success = bootstrap_target_account(account_id, account_region, principal)

        if success:
            success_count += 1

        print()

    print("==========================================")
    print(f"✅ Bootstrap process completed ({success_count}/{len(config['accounts'])} accounts)")
    print("==========================================")

    return 0


if __name__ == "__main__":
    sys.exit(main())
